# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Statistical Intuitions for Social Scientists
author: ""
copyright: ""
logo: "logo25.png"
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: false
  allow_errors: true
  exclude_patterns:
    - 'resources/*'
    - 'lectures/*'
    - 'labs/1/*'
    - 'labs/2/*'
    - 'labs/3/*'
    - 'labs/4/*'
    - 'labs/5/*'
    - 'labs/6/*'
    - 'labs/7/*'
    - 'labs/8/*'
    - 'labs/9/*'

parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - linkify
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https]
  myst_dmath_double_inline: true

html:
  favicon: images/favicon.ico
  use_edit_page_button: false
  use_repository_button: false
  use_issues_button: false
  use_multitoc_numbering: false
  home_page_in_navbar: true
  extra_footer: |
   <p>
   Please cite: Le, K., Jadhav, A. & Jolly, E. (2025). <em>Statistical Intuitions for Social Scientists.</em> <a href="">DOI</a>
   </p>
   <p>
    © 2025 <a href="https://eshinjolly.com">Eshin Jolly</a>. This work is licensed under a Create Commons Attribution-ShareAlike 4.0 International License (CC BY-SA 4.0)
   </p>

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/psyc201b/PSYC-201B  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  jupyterhub_url: "https://datahub.ucsd.edu"
  notebook_interface: "jupyterlab"

sphinx:
  config:
    html_show_copyright: false
    html_extra_path: ['assets','slides']
    bibtex_reference_style: author_year